title: GitHub Pages With Jekyll Tutorial
author: Timur Hassan
email: timur.hassan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm creating this paragraph by modifying the _config.yml file
  in my repo.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
